version: '3.8'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: transaction_db
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database

  src:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgrespass@database:5432/transaction_db"
    links:
      - database
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: always
